name: build docs and deploy

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v1
    - 
      name: Build
      run: |
        mkdir -p docs
        chmod 777 -R ./docs/
        docker run --rm --volume="$PWD:/srv/jekyll" -i jekyll/builder:3.8 jekyll build
    - 
      name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #Remove local and remote branch
        git branch -D docs_build &>/dev/null || true
        git push origin --delete docs_build &>/dev/null || true
        
        #Create branch that will server as the source of the PR
        git checkout -b docs_build
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}users.noreply.github.com"
        git add -A
        git commit -m "Automated docs build ${version}" --allow-empty
        REMOTE="https://${GITHUB_ACTOR}:$GITHUB_TOKEN@github.com/${GITHUB_REPOSITORY}.git"
        git push "${REMOTE}" HEAD:docs_build
        
        #install Hub to easily do a PR
        sudo chown root:root /
        sudo snap install hub --classic
        git config --global core.editor vim
        hub pull-request -f -m "Docs build PR" -b ${GITHUB_ACTOR}:master -h ${GITHUB_ACTOR}:docs_build